# Generated by Django 3.1.7 on 2021-03-22 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NPO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='NPO.news'),
        ),
        migrations.AddField(
            model_name='law',
            name='law_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NPO.typelaw'),
        ),
    ]
